### ISSUE TITLE
parallel sort is needed when run ovl_asym_run

### ISSUE THREAD

**Issue by baozg** [PacificBiosciences/pbipa#1]
Hi,

After `pancake` run, the `ovl_asym_run.sort` is run with `sort`. I recommended use the `sort --parallel` to speed up this process. Also, if the `ovl.m4` is very big, it is safe to set the buffer size to use less memory with `-S` parameters.

**Comment by isovic** [comment]
Hi @baozg ! Thank you very much for the suggestion!
We'll try to incorporate it.
Best regards,
Ivan.

**Comment by pb-cdunn** [comment]
We've recorded your suggestion internally and we will look into it soon.

We are about to delete the Issues board here, as management prefers to keep all our Bioconda tickets in the same location:

* https://github.com/PacificBiosciences/pbbioconda/issues
